### PR TITLE
Create command "sitediff version"

### PR DESCRIPTION
**Pull request by jigarius**
* Creates command `sitediff version`
* Updates version string to `1.0.0` since SiteDiff's now stable enough

### CODE REVIEW

**Comment by jigarius** [comment]
@fbarbanson I wonder why the tests won't pass. I think I'll have to discuss this with you.

**Comment by fbarbanson** [comment]
Rubocop is failing. Click on the little red cross in the build report.

**Comment by fbarbanson** [comment]
Need to fix Rubocop errors.

**Comment by jigarius** [comment]
Francois, now I understand the situation better. I will create a new PR for addressing the `rubocop_todo.yml` issues. For now, I have configured 2 rubocop rules:

* `Metrics/MethodLength`: This controls the max number of lines a method can have. I've set it to 128, along with a nice comment. This is a long-term fix, so I've removed the relevant item from the `todo.yml`
* `Metrics/ClassLength`: This controls the max number of lines a class can have. IMO, a class can have as many methods as the situation warrants. As long as the methods are of a sensible length, things should stay clean. I have disabled this one as a long-term solution.

**Comment by jigarius** [comment]
Did a force-push to squash some commits 😇

**Pull request merged**
