### PR TITLE
Modify Dockerfile to work with required version of Ruby

### PR DESCRIPTION
**Pull request by quentinsf**
The current Dockerfile wouldn't work for me because sitediff wanted a newer version of ruby.

I don't know enough about Ruby to know the best way to do this. My solution was to update ubuntu to 16.04, add a new debian repository source, and get ruby2.5 from there.  

There's probably a much more 'official' solution, so do feel free to discard this PR; I offer it only as a 'something like this is needed to make it work' comment!

Now running on my Mac - thanks!

### CODE REVIEW

**Comment by quentinsf** [comment]
In case it's useful, I've added a Dockerfile to build using Alpine rather than Ubuntu: much easier!
And a README for Docker.

**Comment by zl2** [comment]
Thank you for noticing this error and suggesting a fix for it!

I think something was already done about this in the `dev` branch. We are currently running QA on dev before a merge into master.

I'll ask the person who fixed it to take a look at your PR. In the meantime, feel free to try out dev to see if the issue is resolved there.

Thanks again!

**Comment by fbarbanson** [comment]
Hi Quentin, sorry we left master untouched so long. You will notice that in the Dev branch we have a more comprehensive version of Dockerfile which includes all the changes you had and then some. The reason for this is that in addition to using Dockerfile, we also use a Makefile and a Thorfile which are the entry points for our normal workflow - see our CI build script [here](https://github.com/evolvingweb/sitediff/blob/dev/.circleci/config.yml) for an example.

**Comment by quentinsf** [comment]
Hi there - great - I'm glad you have it sorted - I should probably have guessed that the master branch wouldn't be the most up to date!  I'm afraid I'm off on vacation starting today so won't have a chance to try it out...

Yes, feel free just to copy across anything that's useful - it may be easiest to do that by hand instead of via a PR - I won't be offended!  I'm sure the ENTRYPOINT stuff should work fine in your Dockerfile.  And you might be interested in trying the Alpine-based Dockerfile too: it results in an image about one third of the size.

I'm glad some of it might be useful!

**Comment by fbarbanson** [comment]
FYI - we are working separately on a revamp of the UI.

**Pull request closed without merging**
